# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-11 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_homepage', '0002_auto_20191103_1837'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
